name = "jaben-stores"
main = "build/index.js" # or wherever your Worker entry point is
compatibility_date = "2025-09-03"

[build]
command = "npm run build"
upload_format = "service-worker" # or "modules" if using ESM
